[mypy]
python_version = 3.13
strict = True
warn_unreachable = True
warn_redundant_casts = True
warn_unused_ignores = True
show_error_codes = True

[mypy-tests.*]
disallow_untyped_defs = False

[mypy-testcontainers.*]
ignore_missing_imports = True
